# SPDX-License-Identifier: Apache-2.0
# Bounty program: https://github.com/zeloras/through-metal-link/issues
# The first independent build of the rig earns $250 — see the bounty issue.
custom: ["https://github.com/zeloras/through-metal-link/issues"]